services:
  hugo:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    environment:
      - TZ=Asia/Seoul

  tidy:
    build: .
    volumes:
      - .:/src
    entrypoint: ["hugo", "mod", "tidy"]
    profiles:
      - tools
